version: "3"
services:
  api-server:
    container_name: atm-simulator-machine
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-atm-db:3306/atm-simulator-machine-db
    ports:
      - "8080:8080"
    networks:
      - atm-simulator-machine-mysql-network
    depends_on:
      - api-db

  api-db:
    container_name: mysql-atm-db
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - atm-simulator-machine-mysql-network
    environment:
      - MYSQL_DATABASE=atm-simulator-machine-db
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=atm-simulator-machine
      - MYSQL_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - '3306:3306'

networks:
  atm-simulator-machine-mysql-network: